# Generated by Django 3.2.7 on 2022-08-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20220823_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=30, null=True)),
                ('Teacher_Email', models.EmailField(max_length=60, null=True)),
                ('Teacher_Gender', models.CharField(choices=[('F', 'female'), ('M', 'male'), ('O', 'Others')], default='F', max_length=30)),
            ],
        ),
    ]
