# Generated by Django 3.2.7 on 2022-08-30 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(default=models.CharField(max_length=300), max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('details', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('TEACHER', 'teacher'), ('STUDENT', 'student')], max_length=100)),
                ('detail_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
